### ISSUE TITLE
venues/explore missing information

### ISSUE THREAD

**Issue by cbanbury** [hownowstephen/php-foursquare#32]
Calling the `venues/explore` endpoint seems to be missing fields such as contact, url despite them showing up on the foursquare website:

https://foursquare.com/developers/explore#req=venues%2Fexplore%3Fnear%3DLondon%2C%20UK

**Comment by hownowstephen** [comment]
I'm seeing the same result, it appears to be a mismatch in how foursquare shows their data in their browser-based explorer. If you look at the documentation https://developer.foursquare.com/docs/api/venues/explore#response-fields for that endpoint's response, it only guarantees  `warning, groups, suggestedRadius, headerLocation, headerFullLocation, headerMessage, id, name, location, categories` as response values.

I was able to get the `contact` portion by doing a separate request to the venue detail page https://api.foursquare.com/v2/venues/4b233922f964a520785424e3 - I'd suggest raising this question with Foursquare as to why their browser explorer is returning data differently from their API. Since I originally wrote the library, it appears they've added tiers of access to their resources, it could be that they show more complete data to paid accounts?
